name: Build

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v4
      
      - name: Setup dotnet 6.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build -c Release

      - name: Save package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src/DemaConsulting.Sbom.TransitiveSpdx/bin/Release/*.nupkg
