name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Release semantic version (1.2.3-rc.4)'
        required: true
      winver:
        description: 'Release windows version (1.2.3.4)'
        required: true

jobs:
  release:
  
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v4
      
      - name: Setup dotnet 6.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: > 
          dotnet build
          -c Release
          -p:Version=${{ github.event.inputs.semver }}
          -p:InformationalVersion=${{ github.event.inputs.semver }}
          -p:AssemblyVersion=${{ github.event.inputs.winver }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: src/DemaConsulting.Sbom.TransitiveSpdx/bin/Release/*.nupkg
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.semver }}

      - name: Publish to Nuget
        run: >
          dotnet nuget push
          src/DemaConsulting.Sbom.TransitiveSpdx/bin/Release/*.nupkg
          --source "https://api.nuget.org/v3/index.json"
          --api-key "${{ secrets.DEMACONSULTINGNUGETKEY }}"
